// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WasmReportDesigner.Server.Data;

namespace WasmReportDesigner.Server.Migrations
{
    [DbContext(typeof(WasmReportContext))]
    [Migration("20210722100906_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WasmReportDesigner.Shared.Catalog", b =>
                {
                    b.Property<int>("RecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CatalogName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecId");

                    b.ToTable("Catalogs");

                    b.HasData(
                        new
                        {
                            RecId = 1,
                            CatalogName = "Performance"
                        },
                        new
                        {
                            RecId = 2,
                            CatalogName = "Sound"
                        },
                        new
                        {
                            RecId = 3,
                            CatalogName = "Lights"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
